Fixup migration
mode file was not migrated, and old atlas-probe directory never
cleaned up.

diff --git a/debian/ripe-atlas-common.prerm b/debian/ripe-atlas-common.prerm
--- a/debian/ripe-atlas-common.prerm
+++ b/debian/ripe-atlas-common.prerm
@@ -1,5 +1,5 @@
 #!/bin/sh
-# postrm script for ripe-atlas-common.
+# prerm script for ripe-atlas-anchor.
 #
 # See: dh_installdeb(1).
 
@@ -11,33 +11,22 @@ set -e
 #DEBHELPER#
 
 # Summary of how this script can be called:
-#        * <postrm> 'remove'
-#        * <postrm> 'purge'
-#        * <old-postrm> 'upgrade' <new-version>
-#        * <new-postrm> 'failed-upgrade' <old-version>
-#        * <new-postrm> 'abort-install'
-#        * <new-postrm> 'abort-install' <old-version>
-#        * <new-postrm> 'abort-upgrade' <old-version>
-#        * <disappearer's-postrm> 'disappear' <overwriter>
+#        * <prerm> 'remove'
+#        * <prerm> 'purge'
+#        * <old-prerm> 'upgrade' <new-version>
+#        * <new-prerm> 'failed-upgrade' <old-version>
+#        * <new-prerm> 'abort-install'
+#        * <new-prerm> 'abort-install' <old-version>
+#        * <new-prerm> 'abort-upgrade' <old-version>
+#        * <disappearer's-prerm> 'disappear' <overwriter>
 #          <overwriter-version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package.
 
 case "${1}" in
-	purge)
+	purge|remove|upgrade)
 		rm -f \
-			run/ripe-atlas/pids/* \
-			run/ripe-atlas/status/* \
-			var/spool/ripe-atlas/crons/* \
-			var/spool/ripe-atlas/crons/*/* \
-			var/spool/ripe-atlas/data/* \
-			1>/dev/null 2>&1
-		;;
-
-	remove|upgrade)
-		rm -f \
-			run/ripe-atlas/status/* \
-			usr/libexec/ripe-atlas/scripts/reg_servers.sh \
+			etc/ripe-atlas/reg_servers.sh \
 			1>/dev/null 2>&1
 		;;
 
@@ -45,7 +34,7 @@ case "${1}" in
 		;;
 
 	*)
-		echo "postrm called with unknown argument '$1'" >&2
+		echo "prerm called with unknown argument '$1'" >&2
 		exit 1
 		;;
 esac
